import pyodbc
import tkinter as tk
from tkinter import ttk
from tkinter import *
from tkinter import messagebox
import tkinter.font as font
con=pyodbc.connect(
    "Driver={SQL Server};"
    "Server=DESKTOP-5E0N47M\SQLEXPRESS;"
    "Database=School Managment System;"
    "Trusted_Connnection=yes;"
)
def courseRegistration():
    win.withdraw()
    a=cours_var.get() #name of student
    b=name_var.get()#fathername of student
    d=Add1_var.get()
    e=Add2_var.get()
    f=Add3_var.get()
    g=Add4_var.get()
    h=Add5_var.get()
    i=Add6_var.get()
    Tot=e+f+g+h+i
    Tot1=Tot*100
    per=Tot1/500
    cursor=con.cursor()
    cursor.execute("insert into MARKS(Rollno,name,marksub1,marksub2,marksub3,marksub4,marksub5) values (?,?,?,?,?,?,?)",(a,b,e,f,g,h,i))
    con.commit()
    win1=Tk()
    win1.title("Student Managment")
    win1.geometry("700x900")
    win1.configure(background="grey")
    labelfont=('times',20,'bold')
    labelfont1=('times',15,'bold')
    labelfont2=('times',18,'bold')
    head=ttk.Label(win1,text="\n\tSCHOOL MANAGEMENT SYSTEM\t\n")
    head.pack()
    head.configure(background="blue",width="150")
    head.config(font=labelfont2)
    head1=ttk.Label(win1,text="Student Marksheet",foreground="black")
    head1.pack()
    head1.configure(background="grey")
    head1.config(font=labelfont1)
    head2=ttk.Label(win1,text="Student Rollno:",foreground="white")
    head2.pack()
    head2.configure(background="grey")
    head2.config(font=labelfont1)
    head5=ttk.Label(win1,text=a)
    head5.pack()
    head5.configure(background="grey")
    head5.config(font=labelfont1)
    head3=ttk.Label(win1,text="\nStudent Name:",foreground="white")
    head3.pack()
    head3.configure(background="grey")
    head3.config(font=labelfont1)
    head6=ttk.Label(win1,text=b)
    head6.pack()
    head6.configure(background="grey")
    head6.config(font=labelfont1)
    head7=ttk.Label(win1,text="Student Class",foreground="white")
    head7.pack()
    head7.configure(background="grey")
    head7.config(font=labelfont1)
    head8=ttk.Label(win1,text=d)
    head8.pack()
    head8.configure(background="grey")
    head8.config(font=labelfont1)
    head4=ttk.Label(win1,text="Marks in Subject 1\t 100:",foreground="white")
    head4.pack()
    head4.configure(background="grey")
    head4.config(font=labelfont1)
    head3=ttk.Label(win1,text=e)
    head3.pack()
    head3.configure(background="grey")
    head3.config(font=labelfont1)
    head9=ttk.Label(win1,text="Marks in Subject 2\t 100:",foreground="white")
    head9.pack()
    head9.configure(background="grey")
    head9.config(font=labelfont1)
    head10=ttk.Label(win1,text=f)
    head10.pack()
    head10.configure(background="grey")
    head10.config(font=labelfont1)
    head11=ttk.Label(win1,text="Marks in Subject 3\t 100:",foreground="white")
    head11.pack()
    head11.configure(background="grey")
    head11.config(font=labelfont1)
    head12=ttk.Label(win1,text=g)
    head12.pack()
    head12.configure(background="grey")
    head12.config(font=labelfont1)
    head13=ttk.Label(win1,text="Marks in Subject 4\t 100:",foreground="white")
    head13.pack()
    head13.configure(background="grey")
    head13.config(font=labelfont1)
    head14=ttk.Label(win1,text=h)
    head14.pack()
    head14.configure(background="grey")
    head14.config(font=labelfont1)
    head15=ttk.Label(win1,text="Marks in Subject 5\t 100:",foreground="white")
    head15.pack()
    head15.configure(background="grey")
    head15.config(font=labelfont1)
    head16=ttk.Label(win1,text=i)
    head16.pack()
    head16.configure(background="grey")
    head16.config(font=labelfont1)
    head17=ttk.Label(win1,text="Total Marks",foreground="white")
    head17.pack()
    head17.configure(background="grey")
    head17.config(font=labelfont1)
    head18=ttk.Label(win1,text=Tot)
    head18.pack()
    head18.configure(background="grey")
    head18.config(font=labelfont1)
    head19=ttk.Label(win1,text="PERSONTAGE:",foreground="white")
    head19.pack()
    head19.configure(background="grey")
    head19.config(font=labelfont1)
    head20=ttk.Label(win1,text=per)
    head20.pack()
    head20.configure(background="grey")
    head20.config(font=labelfont1)
    if per>=80:
        head21=ttk.Label(win1,text="GRADE:",foreground="white")
        head21.pack()
        head21.configure(background="grey")
        head21.config(font=labelfont1)
        head22=ttk.Label(win1,text="A+")
        head22.pack()
        head22.configure(background="grey")
        head22.config(font=labelfont1)
    elif  per>=70 and per<=80:
        head21=ttk.Label(win1,text="GRADE:")
        head21.pack()
        head21.configure(background="grey")
        head21.config(font=labelfont1)
        head22=ttk.Label(win1,text="A")
        head22.pack()
        head22.configure(background="grey")
        head22.config(font=labelfont1)
    elif per>=60 and per<=70:
        head21=ttk.Label(win1,text="GRADE:")
        head21.pack()
        head21.configure(background="grey")
        head21.config(font=labelfont1)
        head22=ttk.Label(win1,text="B")
        head22.pack()
        head22.configure(background="grey")
        head22.config(font=labelfont1)
    elif per>=50 and per<=60:
        head21=ttk.Label(win1,text="GRADE:")
        head21.pack()
        head21.configure(background="grey")
        head21.config(font=labelfont1)
        head22=ttk.Label(win1,text="C")
        head22.pack()
        head22.configure(background="grey")
        head22.config(font=labelfont1)
    elif per>=40 and per<=50:
        head21=ttk.Label(win1,text="GRADE:")
        head21.pack()
        head21.configure(background="grey")
        head21.config(font=labelfont1)
        head22=ttk.Label(win1,text="D")
        head22.pack()
        head22.configure(background="grey")
        head22.config(font=labelfont1)
    else:
        head21=ttk.Label(win1,text="GRADE:")
        head21.pack()
        head21.configure(background="grey")
        head21.config(font=labelfont1)
        head22=ttk.Label(win1,text="FAIL")
        head22.pack()
        head22.configure(background="grey")
        head22.config(font=labelfont1)          
    win1.mainloop()
    myFont = font.Font(size=15)


win=Tk()
win.title("Student Managment")
win.geometry("700x800")
win.resizable(0, 0)
win.configure(background="grey")
labelfont=('times',20,'bold')
labelfont1=('times',15,'bold')
labelfont2=('times',18,'bold')
head=ttk.Label(win,text="\n\tSCHOOL MANAGEMENT SYSTEM\t\n")
head.pack()
head.configure(background="blue",width="200")
head.config(font=labelfont2)
teacher_man=ttk.Label(win,text="\nStudent Managment\n")
teacher_man.pack()
teacher_man.configure(background="grey")
teacher_man.config(font=labelfont1)
head1=ttk.Label(win,text="Student Registration")
head1.pack()
head1.configure(background="grey")
head1.config(font=labelfont1)
myFont = font.Font(size=15)
lab1=ttk.Label(win,text="Rollno:")
lab1.pack()
lab1.configure(background="grey")
lab1.config(font=labelfont2)
cours_var=tk.StringVar()
corus_ent=ttk.Entry(win,width=30,textvariable=cours_var)
corus_ent.pack()
corus_ent.config(font=labelfont1)
lab2=ttk.Label(win,text="Student Name")
lab2.pack()
lab2.configure(background="grey")
lab2.config(font=labelfont2)
name_var=tk.StringVar()
name_ent=ttk.Entry(win,width=30,textvariable=name_var)
name_ent.pack()
name_ent.config(font=labelfont1)
lab4=ttk.Label(win,text="Class ")
lab4.pack()
lab4.configure(background="grey")
lab4.config(font=labelfont2)
Add1_var=tk.StringVar()
Add1_ent=ttk.Entry(win,width=30,textvariable=Add1_var)
Add1_ent.pack()
Add1_ent.config(font=labelfont1)
lab5=ttk.Label(win,text=" Marks in Subjects")
lab5.pack()
lab5.configure(background="grey")
lab5.config(font=labelfont2)
Add2_var=tk.IntVar()
Add2_ent=ttk.Entry(win,width=30,textvariable=Add2_var)
Add2_ent.pack()
Add2_ent.config(font=labelfont1)
Add3_var=tk.IntVar()
Add3_ent=ttk.Entry(win,width=30,textvariable=Add3_var)
Add3_ent.pack()
Add3_ent.config(font=labelfont1)
Add4_var=tk.IntVar()
Add4_ent=ttk.Entry(win,width=30,textvariable=Add4_var)
Add4_ent.pack()
Add4_ent.config(font=labelfont1)
Add5_var=tk.IntVar()
Add5_ent=ttk.Entry(win,width=30,textvariable=Add5_var)
Add5_ent.pack()
Add5_ent.config(font=labelfont1)
Add6_var=tk.IntVar()
Add6_ent=ttk.Entry(win,width=30,textvariable=Add6_var)
Add6_ent.pack()
Add6_ent.config(font=labelfont1)
sub_butt=Button(win,text="Generate Marksheet",command=courseRegistration)
sub_butt['font'] = myFont
sub_butt.pack(pady=10)
sub_butt.configure(width="20") 
win.mainloop()