import pyodbc
import tkinter as tk
from tkinter import ttk
from tkinter import *
from tkinter import messagebox
import tkinter.font as font
con=pyodbc.connect(
    "Driver={SQL Server};"
    "Server=DESKTOP-5E0N47M\SQLEXPRESS;"
    "Database=School Managment System;"
    "Trusted_Connnection=yes;"
)
def courseRegistration():
    win.withdraw()
    labelfont3=('times',20,'bold')
    a=cours_var.get() #name of student
    b=name_var.get()#fathername of student
    c=Add_var.get()#email
    d=Add1_var.get()
    e=Add2_var.get()
    f=Add3_var.get()
    g=Add4_var.get()
    h=Add5_var.get()
    i=Add6_var.get()
    j=Add7_var.get()
    cursor=con.cursor()
    cursor.execute("insert into student (Rollno,studentname,grade,Class,sub1,sub2,sub3,sub4,sub5,feesstat) values (?,?,?,?,?,?,?,?,?,?)",(a,b,c,d,e,f,g,h,i,j))
    con.commit()
    messagebox.showinfo("information","DATA ADDED")

win=Tk()
win.title("Student Managment")
win.geometry("700x800")
win.resizable(0, 0)
win.configure(background="grey")
labelfont=('times',20,'bold')
labelfont1=('times',15,'bold')
labelfont2=('times',18,'bold')
head=ttk.Label(win,text="\n\tSCHOOL MANAGEMENT SYSTEM\t\n")
head.pack()
head.configure(background="blue",width="200")
head.config(font=labelfont2)
teacher_man=ttk.Label(win,text="\nStudent Managment\n")
teacher_man.pack()
teacher_man.configure(background="grey")
teacher_man.config(font=labelfont1)
head1=ttk.Label(win,text="Student Registration")
head1.pack()
head1.configure(background="grey")
head1.config(font=labelfont1)
myFont = font.Font(size=15)
lab1=ttk.Label(win,text="Rollno:")
lab1.pack()
lab1.configure(background="grey")
lab1.config(font=labelfont2)
cours_var=tk.StringVar()
corus_ent=ttk.Entry(win,width=30,textvariable=cours_var)
corus_ent.pack()
corus_ent.config(font=labelfont1)
lab2=ttk.Label(win,text="Student Name")
lab2.pack()
lab2.configure(background="grey")
lab2.config(font=labelfont2)
name_var=tk.StringVar()
name_ent=ttk.Entry(win,width=30,textvariable=name_var)
name_ent.pack()
name_ent.config(font=labelfont1)
lab3=ttk.Label(win,text="Grade")
lab3.pack()
lab3.configure(background="grey")
lab3.config(font=labelfont2)
Add_var=tk.StringVar()
Add_ent=ttk.Entry(win,width=30,textvariable=Add_var)
Add_ent.pack()
Add_ent.config(font=labelfont1)
lab4=ttk.Label(win,text="Class ")
lab4.pack()
lab4.configure(background="grey")
lab4.config(font=labelfont2)
Add1_var=tk.StringVar()
Add1_ent=ttk.Entry(win,width=30,textvariable=Add1_var)
Add1_ent.pack()
Add1_ent.config(font=labelfont1)
lab5=ttk.Label(win,text="Subjects")
lab5.pack()
lab5.configure(background="grey")
lab5.config(font=labelfont2)
Add2_var=tk.StringVar()
Add2_ent=ttk.Entry(win,width=30,textvariable=Add2_var)
Add2_ent.pack()
Add2_ent.config(font=labelfont1)
Add3_var=tk.StringVar()
Add3_ent=ttk.Entry(win,width=30,textvariable=Add3_var)
Add3_ent.pack()
Add3_ent.config(font=labelfont1)
Add4_var=tk.StringVar()
Add4_ent=ttk.Entry(win,width=30,textvariable=Add4_var)
Add4_ent.pack()
Add4_ent.config(font=labelfont1)
Add5_var=tk.StringVar()
Add5_ent=ttk.Entry(win,width=30,textvariable=Add5_var)
Add5_ent.pack()
Add5_ent.config(font=labelfont1)
Add6_var=tk.StringVar()
Add6_ent=ttk.Entry(win,width=30,textvariable=Add6_var)
Add6_ent.pack()
Add6_ent.config(font=labelfont1)
lab6=ttk.Label(win,text="Fees Status")
lab6.pack()
lab6.configure(background="grey")
lab6.config(font=labelfont2)
Add7_var=tk.StringVar()
Add7_ent=ttk.Entry(win,width=30,textvariable=Add7_var)
Add7_ent.pack()
Add7_ent.config(font=labelfont1)
sub_butt=Button(win,text="Register",command=courseRegistration)
sub_butt['font'] = myFont
sub_butt.pack(pady=10)
sub_butt.configure(width="15") 
win.mainloop()